//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class intprogfinalEntities : DbContext
    {
        public intprogfinalEntities()
            : base("name=intprogfinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<kullanicitur> kullanicitur { get; set; }
        public virtual DbSet<sabit> sabit { get; set; }
        public virtual DbSet<SM> SM { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<AltSlider> AltSlider { get; set; }
    }
}
