//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sabit
    {
        public int sabitID { get; set; }
        public string logoURL { get; set; }
        public string logoAciklama { get; set; }
        public string siteadi { get; set; }
        public string iletisimtel { get; set; }
        public string haritax { get; set; }
        public string haritay { get; set; }
        public Nullable<bool> silinmedurumu { get; set; }
        public Nullable<System.DateTime> silinmetarihi { get; set; }
        public Nullable<int> silenkullaniciID { get; set; }
    }
}
