//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int SliderID { get; set; }
        public string SliderMetin { get; set; }
        public string SliderResimURL { get; set; }
        public Nullable<bool> SilinmeDurumu { get; set; }
        public Nullable<int> EkleyenKullaniciID { get; set; }
        public Nullable<System.DateTime> EklemeTarihi { get; set; }
        public Nullable<System.DateTime> SilinmeTarihi { get; set; }
        public Nullable<int> SilenKullaniciID { get; set; }
    }
}
