//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM
    {
        public int smID { get; set; }
        public string smadi { get; set; }
        public string smadresi { get; set; }
        public string smiconurl { get; set; }
    }
}
